theme: jekyll-theme-cayman
title: Alyssa Bedell's Portfolio
description: Data analyst with expertise in SQL, Python, and Tableau, passionate about transforming complex data into actionable insights and driving business growth.
